# Generated by Django 4.2.1 on 2024-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.IntegerField()),
                ('node_name', models.CharField(max_length=200)),
                ('degrees', models.FloatField()),
                ('degree_centrality', models.FloatField()),
                ('betweenness', models.FloatField()),
                ('closeness_centrality', models.FloatField()),
                ('page_rank_score', models.FloatField()),
            ],
            options={
                'verbose_name': 'graph_node',
                'verbose_name_plural': 'graph_node',
                'db_table': 'graph_node',
            },
        ),
    ]
