# Generated by Django 4.2.1 on 2024-04-01 09:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crustdb_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_platform', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('disease_stage', models.CharField(max_length=200)),
                ('developmental_stage', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=6)),
                ('cell_type', models.CharField(max_length=200)),
                ('slice_id', models.CharField(max_length=200)),
                ('cell_num', models.IntegerField()),
                ('gene_num', models.IntegerField()),
                ('uniq_data_uid', models.CharField(max_length=200)),
                ('slice_name', models.CharField(max_length=200)),
                ('conformation_num', models.IntegerField()),
                ('repeat_data_uid_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'verbose_name': 'crustdb_main',
                'verbose_name_plural': 'crustdb_main',
                'db_table': 'crustdb_main',
            },
        ),
    ]
