# Generated by Django 4.2.1 on 2024-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crustdb_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uid', models.CharField(max_length=200)),
                ('cell_type', models.CharField(max_length=200)),
                ('slice_id', models.CharField(max_length=200)),
                ('ST_platform', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('developmental_stage', models.CharField(max_length=200)),
                ('disease_steps', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=6)),
                ('slice_name', models.CharField(max_length=200)),
                ('cell_num', models.IntegerField(blank=True, null=True)),
                ('gene_num', models.IntegerField(blank=True, null=True)),
                ('gene_filter_threshold', models.FloatField()),
                ('anchor_gene_proportion', models.FloatField()),
                ('inferred_trans_center_num', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'crustdb_main',
                'verbose_name_plural': 'crustdb_main',
                'db_table': 'crustdb_main',
            },
        ),
    ]
