# Generated by Django 4.2.1 on 2024-06-02 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology_id', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('edges', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
                ('average_branching_factor', models.FloatField()),
                ('modularity', models.FloatField()),
                ('span', models.FloatField()),
                ('assortativity', models.FloatField()),
                ('degree_centrality', models.FloatField()),
                ('closeness_centrality', models.FloatField()),
                ('betweenness_centrality', models.FloatField()),
                ('graph_pkl_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
            options={
                'verbose_name': 'graph',
                'verbose_name_plural': 'graph',
                'db_table': 'graph',
            },
        ),
    ]
