# Generated by Django 4.2.1 on 2024-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_data_uid', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'topology',
                'verbose_name_plural': 'topology',
                'db_table': 'topology',
            },
        ),
    ]
