# Generated by Django 4.2.1 on 2024-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology_id', models.IntegerField()),
                ('node_name', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
            options={
                'verbose_name': 'general_node',
                'verbose_name_plural': 'general_node',
                'db_table': 'general_node',
            },
        ),
    ]
