# Generated by Django 4.2.1 on 2024-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=600, null=True)),
                ('author', models.CharField(blank=True, max_length=600, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('abstract', models.CharField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publication',
                'db_table': 'publication',
            },
        ),
    ]
