# Generated by Django 4.2.1 on 2024-03-18 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_data_uid', models.CharField(max_length=200)),
                ('seed', models.IntegerField()),
                ('sample_name', models.CharField(max_length=200)),
                ('gene_filter_threshold', models.FloatField()),
                ('anchor_gene_proportion', models.FloatField()),
                ('task_id', models.CharField(max_length=200)),
                ('inferred_trans_center_num', models.IntegerField()),
                ('distance_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
            options={
                'verbose_name': 'details',
                'verbose_name_plural': 'details',
                'db_table': 'details',
            },
        ),
    ]
