# Generated by Django 4.2.1 on 2024-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='celltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(max_length=200)),
                ('n_slices', models.IntegerField()),
                ('n_cells', models.IntegerField()),
                ('n_conformations', models.IntegerField()),
            ],
            options={
                'verbose_name': 'celltype',
                'verbose_name_plural': 'celltype',
                'db_table': 'celltype',
            },
        ),
    ]
